server:
    port: 9002

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:3000/eureka/
    instance:
        instance-id: zuul-2
        prefer-ip-address: true

spring:
    application:
        name: zuul-server

zuul:
    ignored-services: "*"
    routes:
        mypower:
            serviceId: server-power
            path: /power/**